"""Current create-chain continuation; historical summaries never override current facts."""
import hashlib,json,subprocess,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 source=sha(ROOT/'00_SSOT/KajovoCMLNG_SSOT.md');p=ROOT/'audit/SSOT_REPAIR_CHECKPOINT.json';c=json.loads(p.read_text())
 c.setdefault('historicalCreateBlocks',[])
 if c.get('createBlock')and c['createBlock']not in c['historicalCreateBlocks']:c['historicalCreateBlocks'].append(c['createBlock'])
 c['createBlock']={'status':'PARTIAL','sourceSha256':source,'operationDesignClosure':{'generation.job.create':'OPEN','secret.create':'OPEN'},'checklist':'audit/SSOT_CREATE_CLOSURE_CHECKLIST.json','currentNormativeAdditions':['§12.55','§8.14'],'concreteIntegrated':['Phase membership/locked scan reservation→actual RETRY child root/command/event/outbox/audit/locator COMMIT','Durable exact frozen schema/request policy/authority/implementation archive and historical hydration; immutable accepted pre-root archive and unchanged success transfer','Protected generation rows↔global key/nonce/ciphertext/AAD deferred authority checks','Trusted immutable profile publication→exact SQL descriptor reader→native registry','OWNER credential composite Secret/version FK and deferred currentACTIVE fingerprint consistency','Retained C0locator/C1original frozen scope physical helper','Worker command/context/arguments/target/artifact-byte binding; effect display stays BLOCKED pendingsemantic hydration'],'limitation':'Each fixture scope recorded separately; RETRY auth/opaque input scaffold is not complete authenticated native chain, archive request policy not full kind eligibility, actual systemd source unavailable.'}
 c['currentSourceDocumentSha256']=source;c['continuationInput'].update(verifiedInputHead='905555e47f3547516439a699e262df62cbbec229',verifiedInputSSOTSha256='df3de1b9d3411c9c410f2d7e4274d9d15ff41ec912ee901833bbc124a79ed691',sourceSha256=source,lastVerifiedCommittedBlock=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),lastVerifiedCommittedBlockSSOTSha256=hashlib.sha256(subprocess.check_output(['git','show','HEAD:00_SSOT/KajovoCMLNG_SSOT.md'],cwd=ROOT)).hexdigest(),currentBlock='PRODUCER_ARCHIVE_KEY_REGISTRY_AND_SECRET_PUBLICATION')
 c['currentCreateChecklist']='audit/SSOT_CREATE_CLOSURE_CHECKLIST.json'
 cache=ROOT/'audit/generated/resume-905/coordinator/connected-cache-proof.json'
 if cache.exists():
  z=json.loads(cache.read_text());c['connectedCacheVerification']={'path':cache.relative_to(ROOT).as_posix(),'sha256':sha(cache),'sourceSha256':z['sourceDocumentSha256'],'status':z['status'],'checked':z['checked'],'failed':z['failed'],'stages':z['stages'],'executionScope':'Actual runner; stale source proof invalidates exactly connected consumer; original proof restored'}
 c['nextBlock']={'id':'RETRY_AUTHENTICATED_NATIVE_CHILD_AND_FULL_LEDGER_PRODUCER','scope':'Join actual locked OWNER verifier/current credential to canonical protected native RETRY input, complete49.8 intent/attempt/dispatch/checkpoint/raw-evidence producers, exact classifier and same-TX child freeze. In parallel accepted pre-root archive transfer and trusted Secret-specific context/command/event/outbox/audit/locator producer. Current physical proofs do not supply these missing producers.','inputs':['audit/SSOT_CREATE_CLOSURE_CHECKLIST.json','audit/generated/resume-905/retry/INTEGRATION.md','audit/generated/resume-905/archive/INTEGRATION.md','audit/generated/resume-905/secrets/INTEGRATION.md'],'generationWholeOperation':'OPEN','secretWholeOperation':'OPEN'}
 c['environmentBlockers']=[{'id':'SHARED.CRYPTO.SYSTEMD_SOURCE','type':'ENVIRONMENT','reason':'UID1000/PID1 tail; no manager or bus/credentials socket; actual systemd encrypted host fixture failed. Docker has no cached image; no unapproved registry/privileged workaround used.','evidence':'audit/generated/resume-905/key/systemd-source-proof.json','reproduction':'audit/generated/resume-905/key/run_systemd_isolated_fixture.sh','scope':'Actual isolated root systemd VM, automatically generated fixture credentials only; not OWNER product decision'}]
 c['status']='PARTIAL';c['SSOT_CONTRACT_READY']='BLOCKED';c['IMPLEMENTATION_PRODUCTION_ACCEPTANCE']='NOT_EVALUATED'
 c['productDecisionsRemaining']=[]
 runner=json.loads((ROOT/'audit/generated/repair-2026-09-30/design-current/commands.json').read_text());assert runner['sourceSha256']==source and runner['allCommandsFinished']
 r=json.loads((ROOT/'audit/SSOT_COMPLETION_REGISTER.json').read_text());assert r['sourceDocumentSha256']==source
 matrix=json.loads((ROOT/'audit/phase1-operation-schema-matrix.json').read_text())
 c['currentResults']={'requiredAvailableChecks':len(runner['requiredChecks']),'zeroExits':sum(x['exitCode']==0 for x in runner['commands']),'nonzeroBlockedOrFailed':sum(x['exitCode']!=0 for x in runner['commands']),'validatorExceptions':sum(x['diagnostic']=='VALIDATOR_EXCEPTION'for x in runner['commands']),'timeouts':sum(x['diagnostic']=='TIMEOUT'for x in runner['commands']),'blockedChecks':[x['script']for x in runner['commands']if x['exitCode']!=0],'provenanceDetectorHits':r['coverage']['provenanceDetectorHits'],'pendingLegacyErrorPredicates':258,'remainingStateDictionaryFields':0,'phase4ExposureBlocked':['dashboard.start','dashboard.stop','gen.editSpec'],'mandatorySQLHelperStatus':'BLOCKED_FOUR_GENERIC_HELPERS','PostgreSQLFixtureVersion':'18.6','wholeOperationsClosed':0}
 c['currentInventory']=matrix['summary'];c['commandsEvidence']='audit/generated/repair-2026-09-30/design-current/commands.json'
 c['completionRegisterCoverage']=r['coverage'];c['completionRegister']={'path':'audit/SSOT_COMPLETION_REGISTER.json','sourceSha256':source,'totalRegisteredObligations':len(r['obligations']),'verifiedBoundedObligations':sum(o['state']=='VERIFIED'for o in r['obligations']),'wholeOperationsClosed':0,'limitation':'Overlapping scopes; bounded verification and regenerated inventory are not whole operation closure.'}
 c['integratedChainProofs']={}
 from sys import path as imports
 imports.insert(0,str(ROOT/'scripts'));from verify_producer_archive_handoffs import PROOFS
 for label,name in PROOFS.items():
  q=json.loads((ROOT/name).read_text());c['integratedChainProofs'][label]={'path':name,'sha256':sha(ROOT/name),'executionSource':q.get('sourceDocumentSha256',q.get('sourceSha256')),'checked':q.get('checked',q.get('checkCount',len(q.get('checks',[])))),'failed':q.get('failed',q.get('failedCount',0)),'scope':q.get('scope',q.get('limitations',q.get('limits','Bounded independent fixture')))}
 c['historicalPriorRunnerResumeVerification']=c.get('runnerResumeVerification')
 c['runnerResumeVerification']={'sourceSha256':source,'universe':len(runner['requiredChecks']),'PASS':c['currentResults']['zeroExits'],'BLOCKED_OR_FAILED':c['currentResults']['nonzeroBlockedOrFailed'],'validatorExceptionsOrTimeouts':[x['script']for x in runner['commands']if x['diagnostic']in ['TIMEOUT','VALIDATOR_EXCEPTION']],'evidence':c['commandsEvidence'],'scope':'Complete available regression universe; full normative checklist remains separately BLOCKED.'}
 c['metricsBeforeAfter']={'entryCheckpoint':'905555e','before':{'checks':48,'PASS':41,'BLOCKED':7,'genericBoundaries':1500,'requestGeneric':500,'responseGeneric':500,'eventGeneric':500,'genericRoutes':500,'unresolvedReferences':242,'operationsWithUnresolvedReferences':121,'unspecifiedEventApplicability':152,'openNamedStateFields':0,'UIExposureBlockers':3,'genericSQLHelpers':4,'legacyErrorPredicatesPending':258,'provenanceDetectorHits':175,'wholeOperationsClosed':0},'after':{'checks':49,'PASS':42,'BLOCKED':7,'genericBoundaries':matrix['summary']['genericBoundaryDefinitions'],'requestGeneric':500,'responseGeneric':500,'eventGeneric':500,'genericRoutes':matrix['summary']['genericRoutes'],'unresolvedReferences':matrix['summary']['unresolvedOperationReferences'],'operationsWithUnresolvedReferences':matrix['summary']['operationsWithUnresolvedReferences'],'unspecifiedEventApplicability':matrix['summary']['unspecifiedEventApplicability'],'openNamedStateFields':0,'UIExposureBlockers':3,'genericSQLHelpers':4,'legacyErrorPredicatesPending':258,'provenanceDetectorHits':r['coverage']['provenanceDetectorHits'],'wholeOperationsClosed':0},'interpretation':'One new connected proof gate; 6 integrated modules and 3 reproduced defects fixed. Broad boundary inventories unchanged. Registry reshaped bounded proof scopes; no project percentage.'}
 c['followUpCoverageDisposition']={'historical':324,'intermediate':318,'current':324,'reason':'Six flag-only tests replaced by six actual native domain-byte violations; coverage disposition retained','authority':'contracts/generation/follow-up-coverage-disposition.json','lostRequiredScenarios':0}
 c['remaining']=['See exact 36 chain duties and agent subobligations in current checklist; none are deferred from A/B to C','242references/1500genericboundaries/500routes/152eventapplicability; four helpers with262 scoped wrappers;258error predicates and175lexical detector hits need semantic review','Three UI exposures/manual visual, full browser/MCP/agents/OpenAI/monitoring and P00-P12 handoffs remain required']
 c['generationMandatoryRemaining']=['See currentExactRemainingIds and currentSubObligationSources; connected CREATE and bounded RETRY commit do not close full producers']
 c['evidenceInvalidation'].update(currentConnectedProof='Actual source/resources/root implementation inputs bound by required verifier and runner cache; old defects retained separately',secretCookieReuse='Old execution source preserved; exact unchanged canonical resource, all helpers, normative Secrets/browser/UI sections and Chromium engine checked. New publication authority fixtures rerun independently.')
 c['createBlock']['connectedCreateProof']='audit/generated/resume-905/archive/review-joined/joined-chain-proof.json'
 c['environmentBlockers'][0]['currentAvailabilityEvidence']='audit/generated/resume-905/archive/review-key/peer-environment-proof.json'
 c['continuationInput']['initialIntegrity']={'entryHead':'905555e47f3547516439a699e262df62cbbec229','entrySource':'df3de1b9d3411c9c410f2d7e4274d9d15ff41ec912ee901833bbc124a79ed691','result':'INTEGRITY_MATCH','entryManifestDigest':'f13444eb1ae62c8dd537550aea7b8bc7b8d9bf910c4da47867a760b494f9d868'}

 c['auxiliaryReviews']={'agentsUsed':6,'input':'905555e / df3de1','outputRoot':'audit/generated/resume-905','reviewMethod':'Independent peer waves due total agent thread limit; authors do not certify their own changes','sharedOwnership':'Only coordinator canonical/projections/register/checkpoint/manifest/Git','independent':['sql/review-consumers','consumers/review-secrets','archive/review-key']}
 # Exact remaining operation/subsystem IDs from reviewed existing source blocks.
 checklist=ROOT/'audit/SSOT_CREATE_CLOSURE_CHECKLIST.json';q=json.loads(checklist.read_text());assert q['sourceSha256']==source
 deps={'GENERATION.ATOMIC.ALL_KINDS':['GENERATION.AUTH.API_ACCEPTANCE','SHARED.CRYPTO.KEY_INVOCATION','SHARED.CRYPTO.GLOBAL_NONCE','GENERATION.ARCHIVE.PRODUCER'],'GENERATION.BASIS.RETRY_CHILD_COMMIT':['GENERATION.BASIS.RETRY_PRODUCER','GENERATION.AUTH.API_ACCEPTANCE','SHARED.CRYPTO.KEY_INVOCATION'],'GENERATION.READ.FULL_NATIVE':['GENERATION.ARCHIVE.HISTORICAL_POLICY','GENERATION.ATOMIC.ALL_KINDS'],'SECRET.ATOMIC.COMMAND_ROOT':['SECRET.AUTH.LOCKED_ACCEPTANCE','SHARED.CRYPTO.KEY_INVOCATION'],'SECRET.AUTH.LOCKED_ACCEPTANCE':['SECRET.REGISTRY.PUBLICATION'],'SECRET.READ.IMMUTABLE':['SECRET.ATOMIC.COMMAND_ROOT','SHARED.CRYPTO.KEY_INVOCATION'],'SHARED.CRYPTO.KEY_INVOCATION':['SHARED.CRYPTO.SYSTEMD_SOURCE']}
 current_missing={
 'GENERATION.BASIS.RETRY_CHILD_COMMIT':'Join genuine locked OWNER authentication/native protected input and full49.8 producer gates to the proven same-TX scan/reservation/child commit',
 'GENERATION.ATOMIC.ALL_KINDS':'Native authenticated UPDATE/RETRY/REPAIR/FOLLOW_UP decisions joined through protected input/full producer gates; bounded internal CREATE auth/crypto/archive/read fixture does not prove genuine systemd source',
 'GENERATION.ARCHIVE.PRODUCER':'Trusted deployment/release/admission archive publisher and full kind-policy dependency producers; success/pre-root exact retention and transfer primitives now verified',
 'GENERATION.ARCHIVE.HISTORICAL_POLICY':'Full archived selector/eligibility/execution domain policy dispatch; two request rules and exact retained historical schema already verified',
 'GENERATION.READ.FULL_NATIVE':'Full public native children/retained error recovery/UI semantic consumers/all kind policies; internal39-column SQL and archived CREATE request consumer already verified',
 'SECRET.REGISTRY.PUBLICATION':'Trusted reviewed release producer and invoker capability assignment under actual locked acceptance; immutable publication/archive/exact reader primitive verified',
 'SECRET.OWNER_CREDENTIAL':'Atomic verifier-hash/version/monotonic-epoch and activation CAS rotation producer; scoped Secret/version FK and currentACTIVE fingerprint guards verified',
 'SHARED.CRYPTO.GLOBAL_NONCE':'Genuine manager key authority producer, typed Secret row reservation and complete rotation/concurrent lifecycle joins; generation exact row/reservation AAD fixture already verified'
 }
 for o in q['obligations']:
  if o['id']in current_missing:o['missing']=current_missing[o['id']]
  o['dependencies']=deps.get(o['id'],[]);o['proofRequirements']=[{'layer':'MANDATORY_PREGEN_FIXTURE','method':o['verification'],'state':'OPEN'}]
  if o['id']in ['GENERATION.BASIS.RETRY_CHILD_COMMIT','GENERATION.ARCHIVE.PRODUCER','GENERATION.ARCHIVE.HISTORICAL_POLICY','SECRET.REGISTRY.PUBLICATION','SECRET.OWNER_CREDENTIAL','SHARED.CRYPTO.GLOBAL_NONCE','UI.DASHBOARD_START.JOIN','UI.DASHBOARD_STOP.JOIN','UI.GEN_EDIT_SPEC.JOIN']:o['state']='IN_PROGRESS'
 q['remainingSubObligations']={}
 for area in ['retry','archive','key','secrets','consumers']:
  rows=[]
  for line in (ROOT/'audit/generated/resume-905'/area/'INTEGRATION.md').read_text().splitlines():
   m=re.match(r'^\s*(?:-\s*|\|\s*)(?:\*\*|`)?((?:GEN\.|GENERATION[._]|SECRET[-_]|KEY_|UI\.|BROWSER\.)[A-Z0-9_.-]+)(?:\*\*|`)?\s*(?::|\||\().*',line)
   if not m:continue
   state='VERIFIED'if m[1]in ['GENERATION.ARCHIVE.SUCCESS','GENERATION.ARCHIVE.REVIEW']else'BLOCKED'if m[1]=='GENERATION_KEY_SYSTEMD_SOURCE_FIXTURE'else'OPEN'
   rows.append({'id':m[1],'authorityAndMissing':line,'state':state,'source':'audit/generated/resume-905/'+area+'/INTEGRATION.md','scope':'Bounded successful archive and independent current review only'if state=='VERIFIED'else'Exact missing producer/test stated in source line'})
  if area=='archive':
   for row in rows:
    if row['id']=='GENERATION.ARCHIVE.PREROOT':
     row['historicalSourceStatement']=row.pop('authorityAndMissing');row.update(state='IN_PROGRESS',authorityAndMissing='§§12.54/12.55: physical pre-root archive and exact success transfer verified; actual trusted acceptance/decision producer and protected retained outcome consumer remain mandatory',source='audit/generated/resume-905/archive/preroot-transfer/INTEGRATION.md',evidence='audit/generated/resume-905/sql/review-preroot-archive/independent-transfer-proof.json')
  q['remainingSubObligations'][area]=rows
 q['additionalBoundedProofs']=[{'id':'GENERATION.ARCHIVE.PREROOT.STORAGE_TRANSFER','state':'VERIFIED','authority':['00_SSOT/KajovoCMLNG_SSOT.md#section.12.54','00_SSOT/KajovoCMLNG_SSOT.md#section.12.55'],'evidence':'audit/generated/resume-905/sql/review-preroot-archive/independent-transfer-proof.json','scope':'Actual canonical accepted snapshot/archive and unchanged later success transfer only; producer/decision/key/public read dependencies remain OPEN'}]
 q['requiredWholeClosure']='No entire operation marked VERIFIED until every own/shared mandatory A/B condition is discharged by source-bound independent proof.'
 checklist.write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n');c['currentExactRemainingIds']=[o['id']for o in q['obligations']if o['state']!='VERIFIED'];c['currentSubObligationSources']=q['remainingSubObligations']
 p.write_text(json.dumps(c,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'source':source,'status':'PARTIAL','knownChainDuties':len(q['obligations']),'wholeClosed':0}))
if __name__=='__main__':main()
