"""Coordinator continuation checkpoint; embeds prior HEAD, never its own commit."""
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def load(p):return json.loads((ROOT/p).read_text())
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
def main():
 path=ROOT/'audit/SSOT_REPAIR_CHECKPOINT.json';c=json.loads(path.read_text());source=sha('00_SSOT/KajovoCMLNG_SSOT.md');runner=load('audit/generated/repair-2026-09-30/design-current/commands.json');r=load('audit/SSOT_COMPLETION_REGISTER.json');assert runner['sourceSha256']==source and runner['allCommandsFinished'] and r['sourceDocumentSha256']==source
 previous=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip()
 c['sourceDocumentSha256']=c['currentSourceDocumentSha256']=source
 c['historicalPriorCurrentResults']=c.get('historicalPriorCurrentResults',c['currentResults'])
 results={'requiredAvailableChecks':len(runner['requiredChecks']),'zeroExits':sum(x['exitCode']==0 for x in runner['commands']),'nonzeroBlockedOrFailed':sum(x['exitCode']!=0 for x in runner['commands']),'validatorExceptions':sum(x['diagnostic']=='VALIDATOR_EXCEPTION' for x in runner['commands']),'timeouts':sum(x['diagnostic']=='TIMEOUT'for x in runner['commands']),'blockedChecks':[x['script'] for x in runner['commands'] if x['exitCode']!=0],'provenanceDetectorHits':r['coverage']['provenanceDetectorHits'],'pendingLegacyErrorPredicates':r['coverage']['errorPredicatesNeedingExplicitReview'],'remainingStateDictionaryFields':0,'phase4ExposureBlocked':['dashboard.start','dashboard.stop','gen.editSpec'],'mandatorySQLHelperStatus':'BLOCKED_FOUR_GENERIC_HELPERS','PostgreSQLFixtureVersion':'18.6','PostgreSQLFixtureLimit':'Named disposable fixture results; full generic helpers/token verifier/crypto/producer joins remain required'}
 for name,script,filename in [('createRequest','verify_create_operation_requests','create-request-tests.json'),('createCompletion','verify_create_completion','create-completion.json'),('createHttpError','verify_create_http_errors','create-http-errors.json'),('followUp','verify_follow_up_contracts','follow-up-tests.json'),('generationAdmission','verify_generation_admission_basis','generation-admission-current-tests.json'),('ownState','verify_operation_state_receipts','operation-state-tests.json')]:
  p='audit/generated/repair-2026-09-30/design-current/'+script+'/'+filename
  if not (ROOT/p).exists():
   files=list((ROOT/('audit/generated/repair-2026-09-30/design-current/'+script)).glob('*.json'));assert len(files)==1,(script,files);p=files[0].relative_to(ROOT).as_posix()
  proof=load(p);results[name]={'checked':proof.get('checked',len(proof.get('checks',[]))),'failed':proof.get('failed'),'evidence':p,'sha256':sha(p)}
 c['currentResults']=results;c['currentInventory']=load('audit/phase1-operation-schema-matrix.json')['summary'];c['completionRegisterCoverage']=r['coverage'];c['completionRegister']={'path':'audit/SSOT_COMPLETION_REGISTER.json','sourceSha256':source,'wholeOperationsClosed':0,'totalRegisteredObligations':len(r['obligations']),'verifiedBoundedObligations':sum(o['state']=='VERIFIED'for o in r['obligations']),'limitations':'Overlapping inventory; bounded proof is not whole operation closure.'}
 c['status']='PARTIAL';c['remainingLifecycleFields']=[];c['remainingLifecycleReview']={'dictionaryFieldsOpen':0,'wholeAffectedOperations':'OPEN','mandatory':'Trusted worker evidence, real finalization/fence/SQL/receipt joins remain required'}
 c['continuationInput'].update(sourceSha256=source,currentBlock='GENERATION_NATIVE_BASIS_AND_FOLLOW_UP_CONTENT',lastVerifiedCommittedBlock=previous,resumeHeadRule='Resolve actual local and remote HEAD; checkpoint embeds only prior committed HEAD, not own resulting commit')
 c.setdefault('verifiedBlockCommits',{})['generationNativeBasisPredecessor']=previous
 c['commandsEvidence']='audit/generated/repair-2026-09-30/design-current/commands.json';c['evidenceInvalidation']={'sourceSha256':source,'allExplicitChecks':'RERUN_CURRENT_SOURCE_SUPPORT_AND_ENVIRONMENT','originalAttempt':'audit/generated/resume-d362/coordinator/design-first-pass-with-follow-up-timeout.json','timeoutResolution':'Actual-schema compilation cache keyed by exact raw schema bytes/root; fresh mutable fixture records and immutable registry only. Original240s timeout retained; final result is separate.','visual':'Exact unchanged consumed UI/schema/requirements and screenshot bytes reused; whole-document rebind is not a rerender or runtime proof'}
 c['nextBlock']={'id':'GENERATION_PHYSICAL_ROOT_AND_ATOMIC_HANDOFF','scope':'Integrate reviewed current39-column root,56-field auth/pin context and operation-scoped command binding; actual PostgreSQL joined fixture from canonical bytes including locator/audit/outbox/replay. Preserve required constant-time API verifier, full locked RETRY membership and native graph/consumer predicates as precise OPEN.','files':['audit/generated/resume-d362/persistence/INTEGRATION.md','audit/generated/resume-d362/review/generation-command-links-corrected.sql','audit/generated/resume-d362/events/generation-event-storage-proposed.sql'],'secretParallel':'Integrate reviewed8.12 versioned import/current-route migration, exact compiled schemas and byte-preserving storage/use. Ten limited names approved; full13.15 browser fixture remains mandatory, not optional.'}
 c['draftPR']={'status':'FORBIDDEN','attempt':'gh pr create --draft using supported authenticated CLI','reason':'Post https://api.github.com/graphql: Forbidden','body':'audit/SSOT_REPAIR_DRAFT_PR.md','title':'Repair SSOT generation admission, own state dictionaries and resumable evidence','compareUrl':'https://github.com/karelmartinek-a11y/kajovocmlng/compare/main...ssot-repair-2026-09-30','bypassAttempted':False}
 c['secretVariants']['productApproval']['effectiveActivation']='TEN_LIMITED_NAMES_APPROVED_TECHNICAL_ACTIVATION_PENDING';c['secretVariants']['status']='LIMITED_PROFILE_NAMES_APPROVED';c['secretVariants']['concreteFormatApproval']='LIMITED_NAMES_APPROVED_EXACT_TECHNICAL_ACTIVATION_PENDING';c['secretVariants']['effective']='PENDING_CURRENT_ROUTE_IMPORT_STORAGE_USE_INTEGRATION';c['auxiliaryReviews']={'externalThreadsLaunched':False,'agentsUsed':7,'coordinatorOwnership':'Only coordinator shared/canonical/Git; each agent own nonoverlapping generated folder','SQL':'audit/generated/resume-d362/persistence/INTEGRATION.md','events':'audit/generated/resume-d362/events/INTEGRATION.md','lifecycle':'audit/generated/resume-d362/sql-lifecycle/review.md','UI':'audit/generated/resume-d362/consumers/OWNER_UI_DISPATCH_INTEGRATION.md','Secrets':'audit/generated/resume-d362/secrets/INTEGRATION.md','independent':'audit/generated/resume-d362/review/INDEPENDENT_REVIEW.md','integration':'Current native selectors/FOLLOW_UP content and own dictionaries integrated. Corrected PostgreSQL physical/Secret/UI candidates reviewed, whole operation joins remain OPEN.'}
 c['remaining']=['242 unresolved references in121operations;1500genericboundarydefinitions/500genericroutes;152unspecifiedeventapplicability','Four generic SQL helpers and whole create SQL/failure-before-root/constant-time auth/crypto joins','Full generation graph and source phase locked PostgreSQL membership/classifier producer/consumer semantics','Secret current import route/storage/broker consumers and mandatory full browser-state fixtures','Three UI exposure joins and manual visual conditions; browser/MCP/agent/OpenAI/monitoring/P00–P12 required handoffs','258legacyerrorpredicates and '+str(results['provenanceDetectorHits'])+'lexicalprovenancehits need actual semantic review; counts do not prove defects or completion']
 physical_path='audit/generated/repair-2026-09-30/design-current/verify_generation_physical_handoff/generation-physical-tests.json'
 if (ROOT/physical_path).exists():
  physical=load(physical_path)
  if physical['sourceDocumentSha256']==source and physical['status']=='PASS':
   c['currentResults']['generationPhysical']={'checked':physical['checked'],'failed':physical['failed'],'postgresqlVersion':physical['postgresqlVersion'],'evidence':physical_path,'sha256':sha(physical_path),'scope':physical['scope'],'wholeOperationClosed':False}
   c['continuationInput']['currentBlock']='CANONICAL_GENERATION_PHYSICAL_ROOT_AND_ATOMIC_HANDOFF'
   c['nextBlock']={'id':'GENERATION_AUTHENTICATED_PROTECTED_INPUT_AND_FULL_ELIGIBILITY','scope':'Complete actual constant-time OWNER API verifier under acceptance lock; canonical systemd/master-key/R17 fixture and protected snapshot opening; exact caller channel binding; locked RETRY phase membership with real classifiers; native graph/repair/read/UI consumer predicates and failure-before-root retained outcomes. These remain A mandatory before generation, not future app-only acceptance.','files':['contracts/generation/physical-create-handoff.json','database/generation-create-foundations.sql','audit/generated/resume-d362/persistence/INTEGRATION.md','audit/generated/resume-d362/admission/graph-projection-integration.md'],'secretParallel':'Integrate reviewed8.12 exact import masks/byte-preserving conversion/current create route and consumer declarations; preserve full13.15 browser-state required fixture, explicit OWNER reveal and legacy immutable RAW versions.'}
 c['historicalPriorRunnerResumeVerification']=c.get('historicalPriorRunnerResumeVerification',c.get('runnerResumeVerification'))
 c['runnerResumeVerification']={'sourceSha256':source,'universe':len(runner['requiredChecks']),'PASS':results['zeroExits'],'BLOCKED_OR_FAILED':results['nonzeroBlockedOrFailed'],'validatorExceptionsOrTimeouts':[x['script']for x in runner['commands']if x['diagnostic']in ['TIMEOUT','VALIDATOR_EXCEPTION']],'cacheReuse':0,'commandsExecuted':len(runner['commands']),'evidence':c['commandsEvidence'],'invalidatesOn':'Exact source/scripts/projections, audit environment, required evidence and external PG binaries for physical check'}
 c['createBlock']['remaining']=['Full native graph and exact consumer/repair policies; UPDATE/RETRY/REPAIR own discussion selectors/content validators now integrated','Canonical successful create root/context/command/event/outbox/audit/locator21PG fixture passed; actual token verifier/crypto/full locked scan/failure-before-root/read/UI still required','Ten limited Secret names approved; exact current-route import/storage/use activation and full13.15 browser fixtures required']
 c['createBlock']['metricsBeforeAfter']['scope']='d362 input to current continuation; structurally explicit create request/response/event boundaries preserved, own semantic basis/physical subobligations strengthened'
 c['auxiliaryReviews']['integration']='Own dictionaries, native selectors/FOLLOW_UP content and reviewed canonical12.52physicalSQL integrated. Actual canonical21PG +independent21/8scoped proofs; whole operations and required auth/crypto/fullscan/read/UI remain OPEN. Secret37PG/115reference and UI59PG/109HTTP are reviewed bounded candidates, not whole operations or active profile admission.'
 c['secretVariants']['currentSourceReviewEvidence']='audit/generated/resume-d362/review/INDEPENDENT_REVIEW.md'
 c['SSOT_CONTRACT_READY']='BLOCKED';c['IMPLEMENTATION_PRODUCTION_ACCEPTANCE']='NOT_EVALUATED';c['gates']={'SSOT_CONTRACT_READY':'BLOCKED','IMPLEMENTATION_PRODUCTION_ACCEPTANCE':'NOT_EVALUATED','authority':'SSOT73.7 effective gate precedence preserved; bounded tests do not replace mandatory design/fixture universe'}
 path.write_text(json.dumps(c,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'source':source,'checks':results['requiredAvailableChecks'],'pass':results['zeroExits'],'blocked':results['nonzeroBlockedOrFailed'],'wholeOperationsClosed':0}))
if __name__=='__main__':main()
