"""Continuation overlay after current runner/register, without own commit hashes."""
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=ROOT/'audit/SSOT_REPAIR_CHECKPOINT.json';c=json.loads(p.read_text());source=sha(ROOT/'00_SSOT/KajovoCMLNG_SSOT.md');assert c['currentSourceDocumentSha256']==source
 previous=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip()
 c['continuationInput'].update(verifiedInputHead='34d3a75c47a92ab7d8e0dac84f581549a15445ca',verifiedInputSSOTSha256='2bc1ce83521b398966723169b1523e9a15a350abfb3131c0ff6b8fa8727c2854',sourceSha256=source,lastVerifiedCommittedBlock=previous,currentBlock='GENERATION_AUTHENTICATED_CANONICAL_CHAIN_BOUNDED',initialIntegrity='audit/generated/resume-34d/coordinator/entry-integrity.json')
 c['generationMandatoryRemaining']=[
  'Actual root-owned encrypted systemd credential source and read-only per-invocation fixture; availability report BLOCKED, AES reference not substitute',
  'Actual global key/nonce authority producer and typed generation/Secret protected-row joins; global SQL registry uniqueness alone is bounded',
  'Effective gateway Authorization transport ceiling and full OWNER session material verifier/caller-channel projection',
  'Full49.8 source-ledger producer→locked projection completeness and all classifiers; scan lock held through actual child frozen-lineage commit',
  'UPDATE source-spec relation, complete native graph/delegation/Secret-use/repair evidence and consumer predicates',
  'Durable frozen schema and domain-policy archive; full native/public read children and historical consumer compatibility',
  'Pinned audit archive producer and actual rollback/cancel/unknown/reconciliation decision producers/full recovery matrix',
  'dashboard.start/dashboard.stop/gen.editSpec exact worker→command→result→read joins; manual visual review remains distinct']
 proofs={}
 for area,name in [('auth-crypto','auth-crypto-proof.json'),('auth-crypto','authenticated-full-chain-proof.json'),('auth-crypto','crypto-registry-proof.json'),('review','authenticated-chain-review.json'),('review','crypto-registry-review.json'),('failure-sql','failure-before-root-proof.json'),('failure-sql','pending-transfer-proof.json'),('read-ui','read-chain-proof.json'),('retry-graph','locked-retry-tests.json')]:
  path=ROOT/'audit/generated/resume-34d'/area/name;q=json.loads(path.read_text());assert q.get('sourceDocumentSha256',q.get('sourceSha256'))==source
  proofs[area+'/'+name]={'path':path.relative_to(ROOT).as_posix(),'sha256':sha(path),'checked':q.get('checked',len(q.get('checks',[]))),'failed':q.get('failed',sum(not x['passed']for x in q.get('checks',[]))),'sourceSha256':source,'scope':'Bounded mandatory pre-generation fixture, not whole operation or app acceptance'}
 c['integratedChainProofs']=proofs
 c['currentResults']['generationChain']={'checked':14,'failed':0,'evidence':'audit/generated/resume-34d/review/authenticated-chain-review.json','wholeOperationClosed':False}
 c['followUpCoverageDisposition']={'historical':324,'intermediate':318,'current':324,'reason':'Six flag-only cases replaced by six actual native bytes/domain violations; publication Boolean replaced by missing immutable output declaration','authority':'contracts/generation/follow-up-coverage-disposition.json','lostRequiredScenarios':0}
 c['metricsBeforeAfter']={'entryCheckpoint':'34d3a75','before':{'checks':46,'PASS':39,'BLOCKED':7,'genericBoundaries':1500,'genericRoutes':500,'unresolvedReferences':242,'operationsWithUnresolvedReferences':121,'unspecifiedEventApplicability':152,'openNamedStateFields':0,'UIExposureBlockers':3,'genericSQLHelpers':4,'legacyErrorPredicatesPending':258,'provenanceDetectorHits':164,'wholeOperationsClosed':0},'after':{'checks':c['currentResults']['requiredAvailableChecks'],'PASS':c['currentResults']['zeroExits'],'BLOCKED':c['currentResults']['nonzeroBlockedOrFailed'],'genericBoundaries':c['currentInventory']['genericBoundaryDefinitions'],'genericRoutes':c['currentInventory']['genericRoutes'],'unresolvedReferences':c['currentInventory']['unresolvedOperationReferences'],'operationsWithUnresolvedReferences':c['currentInventory']['operationsWithUnresolvedReferences'],'unspecifiedEventApplicability':c['currentInventory']['unspecifiedEventApplicability'],'openNamedStateFields':0,'UIExposureBlockers':3,'genericSQLHelpers':4,'legacyErrorPredicatesPending':258,'provenanceDetectorHits':c['currentResults']['provenanceDetectorHits'],'wholeOperationsClosed':0},'interpretation':'New independent chain check, bounded content/SQL/auth/read closure. Broad metrics unchanged. Five added provenance lexical hits reflect new historical/retention wording, not five established defects or detector changes. No percentages.'}
 c['auxiliaryReviews']={'agentsUsed':6,'coordinatorOwnership':'Canonical/shared/projections/checkpoint/register/manifests/Git only coordinator','input':'34d3a75 / 2bc1ce83','outputRoot':'audit/generated/resume-34d','integrated':['auth-crypto','failure-sql','retry-graph','read-ui'],'preparedNotYetEffective':['secrets-browser'],'independent':'audit/generated/resume-34d/review/INDEPENDENT_REVIEW.md','noExternalThreadsExpected':True}
 c['nextBlock']={'id':'SECRET_CURRENT_IMPORT_STORAGE_USE_AND_GENERATION_PRODUCER_LINKS','scope':'Integrate approved limited profile masks/parser and exact HTTP import-byte/idempotency path into existing secret.create; preserve RAW and OWNER reveal; trusted review registry and complete Secret root/command/event/outbox/audit/broker remain required. Continue generationMandatoryRemaining, starting actual canonical key/invocation and RETRY producer→child commit.','inputs':['audit/generated/resume-34d/secrets-browser/INTEGRATION.md','audit/generated/resume-34d/secrets-browser/DELIVERY.json','audit/SSOT_CREATE_OPERATION_OBLIGATIONS.md'],'generationWholeOperation':'OPEN','secretWholeOperation':'OPEN'}
 c['evidenceInvalidation']['visual']='Fresh96 current renders after audit dependency change; SQL-only subsequent source changes checked against exact unchanged consumed UI inputs; source-mutation failed attempt retained.'
 c['remaining']=c['generationMandatoryRemaining']+['242references/1500genericboundaries/500genericroutes/152eventapplicability; all remaining whole domain families','Four generic SQL helpers with262 call-site plans;258legacyerrorpredicates and169lexicalprovenance hits require semantic review','Secrets/browser/MCP/agents/OpenAI/monitoring and all13 P00–P12 handoffs']
 c['status']='PARTIAL';c['SSOT_CONTRACT_READY']='BLOCKED';c['IMPLEMENTATION_PRODUCTION_ACCEPTANCE']='NOT_EVALUATED'
 p.write_text(json.dumps(c,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'sourceSha256':source,'priorCommittedHead':previous,'status':'PARTIAL'}))
if __name__=='__main__':main()
